import { useState } from 'react';
import { Activity, AlertTriangle, CheckCircle, XCircle, Info, ShieldAlert, Zap, Send, Sparkles, Check } from 'lucide-react';
import { C, monoFont, type MonitoringSummary } from './theme';

interface SystemMonitorProps {
  summary: MonitoringSummary | null;
  onTriggerAudit: () => void;
}

export default function SystemMonitor({ summary, onTriggerAudit }: SystemMonitorProps) {
  const [feedbackComment, setFeedbackComment] = useState('');
  const [feedbackCategory, setFeedbackCategory] = useState('Kinematics & Reach');
  const [submittingFeedback, setSubmittingFeedback] = useState(false);
  const [evolutionResult, setEvolutionResult] = useState<any>(null);

  const handleSubmitFeedback = async () => {
    if (!feedbackComment.trim()) return;
    setSubmittingFeedback(true);
    try {
      const res = await fetch('http://localhost:3001/api/feedback', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ comment: feedbackComment, category: feedbackCategory })
      });
      const data = await res.json();
      if (data.ok && data.data) {
        setEvolutionResult(data.data);
      }
    } catch (e) {
      console.error('Failed to submit feedback:', e);
    } finally {
      setSubmittingFeedback(false);
    }
  };

  if (!summary) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', color: C.textMuted, gap: 16 }}>
        <Activity size={32} color={C.textDim} />
        <div style={{ fontSize: 14, fontWeight: 600 }}>No Diagnostic Data Available</div>
        <div style={{ fontSize: 12, maxWidth: 300, textAlign: 'center' }}>
          Run an AI diagnostic audit to generate a health summary from recent system logs.
        </div>
        <button
          onClick={onTriggerAudit}
          style={{
            marginTop: 16,
            padding: '8px 16px',
            borderRadius: 8,
            background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
            color: '#fff',
            border: 'none',
            cursor: 'pointer',
            fontWeight: 600,
            display: 'flex',
            alignItems: 'center',
            gap: 8,
            boxShadow: '0 4px 12px rgba(59, 130, 246, 0.3)'
          }}
        >
          <Zap size={14} />
          Run AI Diagnostic Audit
        </button>
      </div>
    );
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'HEALTHY': return C.green;
      case 'DEGRADED': return C.yellow;
      case 'ANOMALOUS': return C.orange;
      case 'CRITICAL': return C.red;
      default: return C.textDim;
    }
  };

  const getSeverityIcon = (severity: string) => {
    switch (severity) {
      case 'INFO': return <Info size={14} color={C.blue} />;
      case 'WARN': return <AlertTriangle size={14} color={C.yellow} />;
      case 'ERROR': return <XCircle size={14} color={C.red} />;
      case 'CRITICAL': return <ShieldAlert size={14} color={C.red} />;
      default: return <Info size={14} color={C.textDim} />;
    }
  };

  const statusColor = getStatusColor(summary.status);

  return (
    <div style={{ padding: 20, display: 'flex', flexDirection: 'column', gap: 20, height: '100%', overflowY: 'auto' }}>
      {/* Header & Health Score */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}>
            <h2 style={{ margin: 0, fontSize: 18, fontWeight: 700, color: C.white }}>System Health Diagnostics</h2>
            <div style={{
              padding: '2px 8px',
              borderRadius: 12,
              background: `${statusColor}20`,
              border: `1px solid ${statusColor}50`,
              color: statusColor,
              fontSize: 10,
              fontWeight: 800,
              letterSpacing: '0.05em'
            }}>
              {summary.status}
            </div>
          </div>
          <div style={{ fontSize: 11, color: C.textMuted, fontFamily: monoFont }}>
            Generated by {summary.model} • {new Date(summary.timestamp * 1000).toLocaleTimeString()}
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontSize: 28, fontWeight: 900, color: statusColor, lineHeight: 1 }}>
              {summary.health_score}<span style={{ fontSize: 14, color: C.textDim }}>/100</span>
            </div>
            <div style={{ fontSize: 9, color: C.textMuted, textTransform: 'uppercase', marginTop: 4 }}>Health Score</div>
          </div>
          <button
            onClick={onTriggerAudit}
            style={{
              padding: '8px 12px',
              borderRadius: 8,
              background: 'rgba(59, 130, 246, 0.1)',
              color: C.blue,
              border: `1px solid rgba(59, 130, 246, 0.3)`,
              cursor: 'pointer',
              fontWeight: 600,
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              fontSize: 11,
              transition: 'all 0.2s'
            }}
            onMouseOver={e => e.currentTarget.style.background = 'rgba(59, 130, 246, 0.2)'}
            onMouseOut={e => e.currentTarget.style.background = 'rgba(59, 130, 246, 0.1)'}
          >
            <Zap size={12} />
            Refresh Audit
          </button>
        </div>
      </div>

      {/* Executive Summary */}
      <div style={{
        background: 'rgba(255,255,255,0.03)',
        border: `1px solid ${C.border}`,
        borderRadius: 12,
        padding: 16,
        fontSize: 13,
        lineHeight: 1.6,
        color: C.text
      }}>
        {summary.executive_summary}
      </div>

      {/* KPI Stats Row */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 12 }}>
        {[
          { label: 'Total Logs', value: summary.stats.total_logs, color: C.text },
          { label: 'Errors', value: summary.stats.errors, color: summary.stats.errors > 0 ? C.red : C.textDim },
          { label: 'Warnings', value: summary.stats.warnings, color: summary.stats.warnings > 0 ? C.yellow : C.textDim },
          { label: 'Guardrail Denies', value: summary.stats.guardrail_denies, color: summary.stats.guardrail_denies > 0 ? C.orange : C.textDim },
          { label: 'Pick Success', value: `${summary.stats.pick_success_rate_pct}%`, color: summary.stats.pick_success_rate_pct < 80 ? C.red : C.green },
        ].map((stat, i) => (
          <div key={i} style={{
            background: 'rgba(0,0,0,0.2)',
            border: `1px solid ${C.border}`,
            borderRadius: 8,
            padding: '12px 16px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center'
          }}>
            <div style={{ fontSize: 18, fontWeight: 800, color: stat.color, fontFamily: monoFont }}>{stat.value}</div>
            <div style={{ fontSize: 9, color: C.textMuted, textTransform: 'uppercase', marginTop: 4, textAlign: 'center' }}>{stat.label}</div>
          </div>
        ))}
      </div>

      {/* Anomalies & Recommendations */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, flex: 1, minHeight: 0 }}>
        
        {/* Anomalies */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          <h3 style={{ fontSize: 12, fontWeight: 700, color: C.textDim, textTransform: 'uppercase', margin: 0 }}>Detected Anomalies</h3>
          <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 8 }}>
            {summary.anomalies.length === 0 ? (
              <div style={{ padding: 16, background: 'rgba(16, 185, 129, 0.05)', border: `1px dashed rgba(16, 185, 129, 0.2)`, borderRadius: 8, color: C.green, fontSize: 12, display: 'flex', alignItems: 'center', gap: 8 }}>
                <CheckCircle size={14} /> No anomalies detected in recent logs.
              </div>
            ) : (
              summary.anomalies.map((anom, i) => (
                <div key={i} style={{
                  background: 'rgba(0,0,0,0.2)',
                  borderLeft: `3px solid ${anom.severity === 'ERROR' || anom.severity === 'CRITICAL' ? C.red : (anom.severity === 'WARN' ? C.yellow : C.blue)}`,
                  borderRadius: '0 8px 8px 0',
                  padding: '10px 12px',
                  display: 'flex',
                  gap: 10,
                  alignItems: 'flex-start'
                }}>
                  <div style={{ marginTop: 2 }}>{getSeverityIcon(anom.severity)}</div>
                  <div>
                    <div style={{ fontSize: 10, fontWeight: 700, color: C.textDim, marginBottom: 4, fontFamily: monoFont }}>[{anom.component.toUpperCase()}]</div>
                    <div style={{ fontSize: 12, color: C.text, lineHeight: 1.4 }}>{anom.description}</div>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Recommendations */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          <h3 style={{ fontSize: 12, fontWeight: 700, color: C.textDim, textTransform: 'uppercase', margin: 0 }}>AI Recommendations</h3>
          <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 8 }}>
            {summary.recommendations.length === 0 ? (
              <div style={{ padding: 16, color: C.textMuted, fontSize: 12, fontStyle: 'italic' }}>
                No specific recommendations at this time.
              </div>
            ) : (
              summary.recommendations.map((rec, i) => (
                <div key={i} style={{
                  background: 'rgba(255,255,255,0.02)',
                  border: `1px solid ${C.border}`,
                  borderRadius: 8,
                  padding: '10px 12px',
                  fontSize: 12,
                  color: C.text,
                  lineHeight: 1.5,
                  display: 'flex',
                  gap: 10
                }}>
                  <div style={{ color: C.blue, fontWeight: 800 }}>{i + 1}.</div>
                  <div>{rec}</div>
                </div>
              ))
            )}
          </div>
        </div>

      </div>

      {/* Operator Feedback & Continuous Skill Evolution Console */}
      <div style={{
        background: 'rgba(255,255,255,0.02)',
        border: `1px solid ${C.border}`,
        borderRadius: 12,
        padding: 16,
        display: 'flex',
        flexDirection: 'column',
        gap: 12
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <Sparkles size={16} color={C.blue} />
            <span style={{ fontSize: 13, fontWeight: 700, color: C.white }}>Operator Feedback & Skill Evolution</span>
          </div>
          <span style={{ fontSize: 11, color: C.textDim, fontFamily: monoFont }}>Autonomous Harness & Guardrail Tuning</span>
        </div>

        {/* Category Selector */}
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          {['Kinematics & Reach', 'Dual-Arm Coordination', 'Grasping & Release', 'VLA Task Planning'].map(cat => (
            <button
              key={cat}
              onClick={() => setFeedbackCategory(cat)}
              style={{
                padding: '4px 10px',
                borderRadius: 6,
                fontSize: 11,
                fontWeight: 600,
                border: feedbackCategory === cat ? `1px solid ${C.blue}` : `1px solid ${C.border}`,
                background: feedbackCategory === cat ? 'rgba(59, 130, 246, 0.2)' : 'rgba(0,0,0,0.2)',
                color: feedbackCategory === cat ? C.blue : C.textMuted,
                cursor: 'pointer',
                transition: 'all 0.15s'
              }}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Comment Textarea & Action */}
        <div style={{ display: 'flex', gap: 10 }}>
          <textarea
            value={feedbackComment}
            onChange={e => setFeedbackComment(e.target.value)}
            placeholder="Type feedback or observed failure (e.g., 'Robot 2 failed IK during LongBar pick; keep Y in front buffer at +0.25m')..."
            rows={2}
            style={{
              flex: 1,
              background: 'rgba(0,0,0,0.3)',
              border: `1px solid ${C.border}`,
              borderRadius: 8,
              padding: '10px 12px',
              color: C.text,
              fontSize: 12,
              fontFamily: 'inherit',
              resize: 'none',
              outline: 'none'
            }}
          />
          <button
            onClick={handleSubmitFeedback}
            disabled={submittingFeedback || !feedbackComment.trim()}
            style={{
              padding: '0 16px',
              borderRadius: 8,
              background: feedbackComment.trim() ? 'linear-gradient(135deg, #3b82f6, #2563eb)' : 'rgba(255,255,255,0.05)',
              color: feedbackComment.trim() ? '#fff' : C.textDim,
              border: 'none',
              cursor: feedbackComment.trim() ? 'pointer' : 'not-allowed',
              fontWeight: 600,
              fontSize: 12,
              display: 'flex',
              alignItems: 'center',
              gap: 8,
              opacity: submittingFeedback ? 0.7 : 1,
              whiteSpace: 'nowrap'
            }}
          >
            {submittingFeedback ? (
              <>
                <Zap size={14} className="animate-spin" /> Evolving...
              </>
            ) : (
              <>
                <Send size={14} /> Submit & Evolve
              </>
            )}
          </button>
        </div>

        {/* Display Evolution Result if available */}
        {evolutionResult && (
          <div style={{
            background: 'rgba(16, 185, 129, 0.05)',
            border: `1px solid rgba(16, 185, 129, 0.25)`,
            borderRadius: 8,
            padding: 12,
            display: 'flex',
            flexDirection: 'column',
            gap: 8,
            marginTop: 4
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, color: C.green, fontSize: 12, fontWeight: 700 }}>
              <Check size={14} /> Skill Evolution Proposal Synthesized & Logged
            </div>
            <div style={{ fontSize: 12, color: C.text }}>
              <strong>Root Cause:</strong> {evolutionResult.root_cause}
            </div>
            {evolutionResult.parameter_patches && Object.keys(evolutionResult.parameter_patches).length > 0 && (
              <div style={{ fontSize: 11, color: C.textDim }}>
                <strong>Parameter Tuning:</strong>
                <ul style={{ margin: '4px 0 0 16px', padding: 0 }}>
                  {Object.entries(evolutionResult.parameter_patches).map(([k, v]) => (
                    <li key={k} style={{ fontFamily: monoFont }}>{k}: {String(v)}</li>
                  ))}
                </ul>
              </div>
            )}
            {evolutionResult.skill_evolution_rules && evolutionResult.skill_evolution_rules.length > 0 && (
              <div style={{ fontSize: 11, color: C.textDim }}>
                <strong>Skill Invariant Rules:</strong>
                <ul style={{ margin: '4px 0 0 16px', padding: 0 }}>
                  {evolutionResult.skill_evolution_rules.map((rule: string, i: number) => (
                    <li key={i}>{rule}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

      </div>
    </div>
  );
}